service: hackathon

provider:
 name: aws
 runtime: nodejs6.10
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1

functions:
 api:
   handler: lib/lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /